#!/usr/bin/env bash
# Writes backend/.env for a first deploy.
#
#   bash deploy/make-env.sh
#
# Everything is filled in except OPENROUTER_API_KEY, which you paste yourself so
# it never passes through anyone else's hands. Refuses to overwrite an existing
# .env — a live one holds a secret key that sessions depend on.
#
# The values here are deliberately LOCAL-ONLY: the app is reachable at
# 127.0.0.1:5000 and nowhere else until you choose how to expose it. Email is
# set to dry-run, so nothing is sent while you are still testing.

set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$repo/backend/.env"

if [ -e "$env_file" ]; then
  echo "refusing to overwrite $env_file"
  echo "move it aside first if you really want a new one:  mv backend/.env backend/.env.old"
  exit 1
fi

admin_email="${CURIO_ADMIN_EMAIL:-}"
if [ -z "$admin_email" ]; then
  read -rp "Admin email (the account you'll sign up with): " admin_email
fi
[ -n "$admin_email" ] || { echo "admin email is required"; exit 1; }

secret="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"

umask 077
cat > "$env_file" <<EOF
# Generated by deploy/make-env.sh. Never commit this file.

# ── Core ───────────────────────────────────────────────────────────────
CURIO_SECRET_KEY=$secret
CURIO_DB=$repo/curio.db
CURIO_STATIC_DIR=$repo/frontend/dist

# Local only for now. Both of these change when you expose the app publicly:
# the URL becomes your real hostname and COOKIE_SECURE goes back to 1.
CURIO_PUBLIC_URL=http://localhost:5000
CURIO_COOKIE_SECURE=0

# ── OpenRouter ─────────────────────────────────────────────────────────
# ↓↓↓ THE ONE LINE YOU MUST FILL IN ↓↓↓
OPENROUTER_API_KEY=
# Starting chain only — re-pick from /admin once you can see what is behaving.
CURIO_MODEL_CHAIN=meta-llama/llama-3.3-70b-instruct:free,google/gemma-2-9b-it:free,mistralai/mistral-7b-instruct:free

# ── Abuse guards ───────────────────────────────────────────────────────
CURIO_DAILY_CAP_USER=300
CURIO_DAILY_CAP_ANON_IP=40
CURIO_SIGNUP_CAP_IP=5

# ── Admin ──────────────────────────────────────────────────────────────
CURIO_ADMIN_EMAIL=$admin_email

# ── Email ──────────────────────────────────────────────────────────────
# Dry run: emails are printed to the log, never sent. Fill in the Gmail app
# password and set DRY_RUN=0 when you actually want the daily doors.
CURIO_MAIL_DRY_RUN=1
CURIO_SMTP_HOST=smtp.gmail.com
CURIO_SMTP_PORT=587
CURIO_SMTP_USER=
CURIO_SMTP_PASSWORD=
CURIO_MAIL_FROM=$admin_email
CURIO_MAIL_FROM_NAME=Curio
EOF

chmod 600 "$env_file"
echo "wrote $env_file (mode 600)"
echo
echo "Now paste your OpenRouter key into the OPENROUTER_API_KEY= line:"
echo "    nano $env_file"
